FROM docker.io/maven:3.9-eclipse-temurin-21-alpine AS builder

WORKDIR /build

COPY pom.xml ./
COPY src ./src

RUN mvn clean package -DskipTests

FROM docker.io/eclipse-temurin:21-jre

WORKDIR /home

COPY --from=builder /build/target/*.jar /home/app.jar

RUN addgroup -g 65532 -S appgroup && \
    adduser -u 65532 -S appuser -G appgroup

USER 65532:65532

ENTRYPOINT ["java", "-jar", "/home/app.jar"]
